# Generated by Django 3.1.3 on 2020-11-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='upload_images',
        ),
    ]
