# Generated by Django 3.1.3 on 2020-11-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201129_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='headImg',
            field=models.ImageField(upload_to='bookRecognition/upload'),
        ),
    ]
